version: "3.8"
services:
  mysql_server:
    container_name: orte-mysql_server
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=orte
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    links:
      - mysql_server
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_server
      PMA_PORT: 3306

  backend:
    container_name: orte-backend
    build:
      context: ./orte-backend
      dockerfile: Dockerfile
    ports:
      - 20000:20000
    depends_on:
      - mysql_server
    environment:
      - MYSQL_HOST=mysql_server
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=orte

  frontend:
    container_name: orte-frontend
    build:
      context: ./orte-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  mysql-data:
