version: "3.8"

services:
  mysql_server:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=orte
    ports:
      - "3306:3306"

      - MYSQL_HOST=mysql_server
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=orte
